server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: es-host-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

host:
  es:
    enabled-versions: ${ES_ENABLED_VERSIONS:8.5,8.13,9.1}
    versions:
      8.5:
        hosts: ${ES_V85_HOSTS:localhost:9200}
        username: ${ES_V85_USERNAME:elastic}
        password: ${ES_V85_PASSWORD:password}
        socket-timeout: ${ES_V85_SOCKET_TIMEOUT_MS:60000}
      8.13:
        hosts: ${ES_V813_HOSTS:localhost:9201}
        username: ${ES_V85_USERNAME:elastic}
        password: ${ES_V85_PASSWORD:password}
        socket-timeout: ${ES_V813_SOCKET_TIMEOUT_MS:60000}
      9.1:
        hosts: ${ES_V91_HOSTS:localhost:9202}
        username: ${ES_V85_USERNAME:elastic}
        password: ${ES_V85_PASSWORD:password}
        socket-timeout: ${ES_V91_SOCKET_TIMEOUT_MS:60000}
